update 20260317_1015_en

diff --git a/majapps-launch-en/majapps-launch-en b/majapps-launch-en/majapps-launch-en
--- a/majapps-launch-en/majapps-launch-en
+++ b/majapps-launch-en/majapps-launch-en
@@ -1,10 +1,14 @@
 #! /usr/bin/env bash
 # filename: majapps-launch.sh
-# 20250917 (en)
-# 20250919 (en) -- added runff var for firefox path
-# 20251017 (en) -- run inside infinite loop and added 'q' to quit
-#               -- keys in separate index-ed array to keep display order
-# last: 20251017 (en)
+# 20250917 en
+# 20250919 en v1 added runff var for firefox path
+# 20251017 en v2 run inside infinite loop and added 'q' to quit
+#                keys in separate index-ed array to keep display order
+# 20260317 en v3 $delline calculated from longest KEY line with get_longest function
+#                sorted output to fzf command
+#                extract KEYS from URLS
+# last: 20260317
+# ---
 
 runff="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe"
 
@@ -25,28 +29,44 @@ declare -A apps=(["Firefox"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/
                  ["URE"]="" \
                  ["Razvojne Rešitve (EN)"]="")
 
-declare -a keys=("Firefox" \
-                 "MS Edge" \
-                 "Google Chrome" \
-                 "MS Calc" \
-                 "Acrobat Reader"
-                 "AutoCAD 2024" \
-                 "Explorer++" \
-                 "Notepad++" \
-                 "MultiCommander" \
-                 "Super Launcher" \
-                 "Nukleus (EN)" \
-                 "URE" \
-                 "Razvojne Rešitve (EN)" \
-                 "q (quit)")
+# array of keys from apps
+keys=("${!apps[@]}") # v3
+
+# functions #v3
+get_longest() {
+	if [ ! $# -eq 1 ]; then
+		echo "[ERROR1] must supply array of sentences as parameter"
+		exit 1
+	fi
+
+	local len=0
+	local longest
+	local -n lines2=$1 # new way: must call array as < array_name >
+
+	for line in "${lines2[@]}"; do
+		llen="${#line}"
+		if [ "${llen}" -gt "${len}" ]; then
+			len="${llen}"
+			longest="${line}"
+		else
+			continue
+		fi
+	done
+
+	echo "${longest}"
+}
+
+# MAIN # v3
+longest_l=$(get_longest keys)                                         # v3
+delline=$(for((i = 0; i < ${#longest_l}; i++)); do printf "-"; done)  # v3
 
 while true; do
-	selection=$(for key in "${!keys[@]}"; do echo "${keys[$key]}"; done | \
+	selection=$((for key in "${!keys[@]}"; do echo "${keys[$key]}"; done | sort; echo "${delline}"; echo "Quit") | \
 		fzf \
-			-e \
-			--reverse \
-			-i \
-			--prompt="launch: ")
+		-e \
+		--reverse \
+		-i \
+		--prompt="launch: ")
 
 	if [ "x${selection}" == "x" ]; then
 		echo -e "[INFO] no selection\n"
@@ -64,7 +84,7 @@ while true; do
 		jhl_ure="https://ris.jhl.si/"
 		# cygstart "${runedg}" ${jhl_ure}
 		"${runedg}" ${jhl_ure}
-	elif [ "${selection}" == "q (quit)" ]; then
+	elif [ "${selection}" == "Quit" ]; then # v3
 		exit
 	else
 		cygstart "${apps["${selection}"]}" &>/dev/null
@@ -92,3 +112,4 @@ done
 # cygstart /c/WINDOWS/System32/rundll32.exe user32.dll LockWorkStation
 # cygstart /c/WINDOWS/System32/rundll32.exe  shell32.dll,Control_RunDLL hotplug.dll
 #############################################
+
